title: Jekyll Minima
description: Jekyll Minima Theme
baseurl: "/" # 仓库名称作为baseurl
url: "" # 这里会根据GitHub Pages自动设置
google_analytics: G-4ZMS4MK5S7
theme: minima
#remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-assets
  - jekyll-paginate
exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
